spring:
  profiles:
    active: dev
    application:
      name: online-shop
server:
  port: 8085
  servlet:
    context-path: /api/v1/shopping-cart

#http://localhost:8085/api/v1/shopping-cart/swagger-ui/index.html
