CREATE TABLE sc_m_order
(
    order_id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_no       VARCHAR(20),
    order_date     date,
    order_time     time WITHOUT TIME ZONE,
    total_item     INTEGER,
    total_amount   FLOAT,
    total_discount FLOAT,
    total_tax      FLOAT,
    total_payable  FLOAT,
    user_id        BIGINT,
    status_id      BIGINT                                  NOT NULL,
    CONSTRAINT pk_sc_m_order PRIMARY KEY (order_id)
);

CREATE TABLE sc_m_order_product
(
    order_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_qty   INTEGER,
    order_id      BIGINT,
    product_id    BIGINT                                  NOT NULL,
    CONSTRAINT pk_sc_m_order_product PRIMARY KEY (order_item_id)
);

CREATE TABLE sc_m_product
(
    product_id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_name     VARCHAR(100),
    product_desc     VARCHAR(200),
    product_code     VARCHAR(10),
    product_price    FLOAT,
    product_quantity INTEGER,
    product_image    VARCHAR(255),
    is_active        BOOLEAN,
    product_discount FLOAT,
    sub_cat_id       BIGINT                                  NOT NULL,
    brand_id         BIGINT                                  NOT NULL,
    CONSTRAINT pk_sc_m_product PRIMARY KEY (product_id)
);

CREATE TABLE sc_m_product_variable_mapping
(
    variable_mapping_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    variable_value      VARCHAR(30),
    variable_id         BIGINT                                  NOT NULL,
    product_id          BIGINT                                  NOT NULL,
    CONSTRAINT pk_sc_m_product_variable_mapping PRIMARY KEY (variable_mapping_id)
);

CREATE TABLE sc_m_shipping_info
(
    shipping_info_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    full_name        VARCHAR(60),
    mobile_no        VARCHAR(15),
    email            VARCHAR(50),
    city             VARCHAR(50),
    province         VARCHAR(50),
    postal_code      VARCHAR(10),
    country          VARCHAR(50),
    address_line_1   VARCHAR(100),
    address_line_2   VARCHAR(100),
    address_line_3   VARCHAR(100),
    is_default       BOOLEAN,
    user_id          BIGINT                                  NOT NULL,
    CONSTRAINT pk_sc_m_shipping_info PRIMARY KEY (shipping_info_id)
);

CREATE TABLE sc_m_shop_cart
(
    shop_cart_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_qty  INTEGER,
    date_added   date,
    time_added   time WITHOUT TIME ZONE,
    product_id   BIGINT                                  NOT NULL,
    user_id      BIGINT                                  NOT NULL,
    CONSTRAINT pk_sc_m_shop_cart PRIMARY KEY (shop_cart_id)
);

CREATE TABLE sc_m_user
(
    user_id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR(50),
    last_name  VARCHAR(50),
    email      VARCHAR(70),
    username   VARCHAR(30),
    password   VARCHAR(200),
    mobile_no  VARCHAR(10),
    is_active  BOOLEAN,
    role_id    BIGINT                                  NOT NULL,
    CONSTRAINT pk_sc_m_user PRIMARY KEY (user_id)
);

CREATE TABLE sc_r_product_brand
(
    brand_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    brand_name VARCHAR(100),
    brand_desc VARCHAR(200),
    CONSTRAINT pk_sc_r_product_brand PRIMARY KEY (brand_id)
);

CREATE TABLE sc_r_product_category
(
    cat_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cat_name VARCHAR(100),
    cat_desc VARCHAR(200),
    cat_code VARCHAR(10),
    type_id  BIGINT                                  NOT NULL,
    CONSTRAINT pk_sc_r_product_category PRIMARY KEY (cat_id)
);

CREATE TABLE sc_r_product_sub_category
(
    sub_cat_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sub_cat_name VARCHAR(100),
    sub_cat_desc VARCHAR(200),
    sub_cat_code VARCHAR(10),
    cat_id       BIGINT                                  NOT NULL,
    CONSTRAINT pk_sc_r_product_sub_category PRIMARY KEY (sub_cat_id)
);

CREATE TABLE sc_r_product_type
(
    type_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type_name VARCHAR(80),
    type_desc VARCHAR(200),
    type_code VARCHAR(10),
    CONSTRAINT pk_sc_r_product_type PRIMARY KEY (type_id)
);

CREATE TABLE sc_r_product_variable
(
    variable_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    variable_name VARCHAR(30),
    CONSTRAINT pk_sc_r_product_variable PRIMARY KEY (variable_id)
);

CREATE TABLE sc_r_role
(
    role_id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(40),
    description VARCHAR(100),
    is_active   BOOLEAN,
    CONSTRAINT pk_sc_r_role PRIMARY KEY (role_id)
);

CREATE TABLE sc_r_status
(
    status_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    status_name VARCHAR(45),
    status_code VARCHAR(5),
    status_type VARCHAR(45),
    CONSTRAINT pk_sc_r_status PRIMARY KEY (status_id)
);

ALTER TABLE sc_m_user
    ADD CONSTRAINT uc_sc_m_user_username UNIQUE (username);

ALTER TABLE sc_r_status
    ADD CONSTRAINT uc_sc_r_status_status_code UNIQUE (status_code);

CREATE UNIQUE INDEX SC_M_PRODUCT_PRODUCT_CODE_UNQ_idx ON sc_m_product (product_code);

CREATE INDEX SC_M_USER_USERNAME_UNQ_idx ON sc_m_user (username);

CREATE UNIQUE INDEX SC_R_PRODUCT_CATEGORY_CAT_CODE_UNQ_idx ON sc_r_product_category (cat_code);

CREATE UNIQUE INDEX SC_R_PRODUCT_SUB_CATEGORY_SUB_CAT_CODE_UNQ_idx ON sc_r_product_sub_category (sub_cat_code);

CREATE UNIQUE INDEX SC_R_PRODUCT_TYPE_TYPE_CODE_UNQ_idx ON sc_r_product_type (type_code);

CREATE UNIQUE INDEX SC_R_STATUS_CODE_UNQ_IDX ON sc_r_status (status_code);

ALTER TABLE sc_m_order
    ADD CONSTRAINT FK_SC_M_ORDER_ON_STATUS FOREIGN KEY (status_id) REFERENCES sc_r_status (status_id);

ALTER TABLE sc_m_order
    ADD CONSTRAINT FK_SC_M_ORDER_ON_USER FOREIGN KEY (user_id) REFERENCES sc_m_user (user_id);

ALTER TABLE sc_m_order_product
    ADD CONSTRAINT FK_SC_M_ORDER_PRODUCT_ON_ORDER FOREIGN KEY (order_id) REFERENCES sc_m_order (order_id);

CREATE INDEX fk_SC_M_ORDER_PRODUCT_SC_M_ORDER1_idx ON sc_m_order_product (order_id);

ALTER TABLE sc_m_order_product
    ADD CONSTRAINT FK_SC_M_ORDER_PRODUCT_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES sc_m_product (product_id);

CREATE INDEX fk_SC_M_ORDER_PRODUCT_SC_M_PRODUCT1_idx ON sc_m_order_product (product_id);

ALTER TABLE sc_m_product
    ADD CONSTRAINT FK_SC_M_PRODUCT_ON_BRAND FOREIGN KEY (brand_id) REFERENCES sc_r_product_brand (brand_id);

CREATE INDEX fk_SC_M_PRODUCT_SC_R_PRODUCT_BRAND1_idx ON sc_m_product (brand_id);

ALTER TABLE sc_m_product
    ADD CONSTRAINT FK_SC_M_PRODUCT_ON_SUB_CAT FOREIGN KEY (sub_cat_id) REFERENCES sc_r_product_sub_category (sub_cat_id);

CREATE INDEX fk_SC_M_PRODUCT_SC_R_PRODUCT_SUB_CATEGORY1_idx ON sc_m_product (sub_cat_id);

ALTER TABLE sc_m_product_variable_mapping
    ADD CONSTRAINT FK_SC_M_PRODUCT_VARIABLE_MAPPING_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES sc_m_product (product_id);

CREATE INDEX SC_M_PRODUCT_VARIABLE_MAPPING_SC_M_PRODUCT1_idx ON sc_m_product_variable_mapping (product_id);

ALTER TABLE sc_m_product_variable_mapping
    ADD CONSTRAINT FK_SC_M_PRODUCT_VARIABLE_MAPPING_ON_VARIABLE FOREIGN KEY (variable_id) REFERENCES sc_r_product_variable (variable_id);

CREATE INDEX SC_M_PRODUCT_VARIABLE_MAPPING_SC_R_VARIABLE1_idx ON sc_m_product_variable_mapping (variable_id);

ALTER TABLE sc_m_shipping_info
    ADD CONSTRAINT FK_SC_M_SHIPPING_INFO_ON_USER FOREIGN KEY (user_id) REFERENCES sc_m_user (user_id);

CREATE INDEX fk_SC_M_SHIPPING_INFO_SC_M_USER1_idx ON sc_m_shipping_info (user_id);

ALTER TABLE sc_m_shop_cart
    ADD CONSTRAINT FK_SC_M_SHOP_CART_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES sc_m_product (product_id);

CREATE INDEX fk_SC_M_SHOP_CART_SC_M_PRODUCT1_idx ON sc_m_shop_cart (product_id);

ALTER TABLE sc_m_shop_cart
    ADD CONSTRAINT FK_SC_M_SHOP_CART_ON_USER FOREIGN KEY (user_id) REFERENCES sc_m_user (user_id);

CREATE INDEX fk_SC_M_SHOP_CART_SC_M_USER1_idx ON sc_m_shop_cart (user_id);

ALTER TABLE sc_m_user
    ADD CONSTRAINT FK_SC_M_USER_ON_ROLE FOREIGN KEY (role_id) REFERENCES sc_r_role (role_id);

CREATE INDEX fk_SC_M_USER_SC_R_ROLE1_idx ON sc_m_user (role_id);

ALTER TABLE sc_r_product_category
    ADD CONSTRAINT FK_SC_R_PRODUCT_CATEGORY_ON_TYPE FOREIGN KEY (type_id) REFERENCES sc_r_product_type (type_id);

CREATE INDEX fk_SC_R_PRODUCT_CATEGORY_SC_R_PRODUCT_TYPE1_idx ON sc_r_product_category (type_id);

ALTER TABLE sc_r_product_sub_category
    ADD CONSTRAINT FK_SC_R_PRODUCT_SUB_CATEGORY_ON_CAT FOREIGN KEY (cat_id) REFERENCES sc_r_product_category (cat_id);

CREATE INDEX fk_SC_R_PRODUCT_SUB_CATEGORY_ST_R_CATEGORY1_idx ON sc_r_product_sub_category (cat_id);